export const themeLightColors = {
  '--theme-generic-font': 'var(--tw-color-zinc-950)',
  '--theme-generic-font-hover': 'var(--tw-color-blue-700)',
  '--theme-generic-font-grayed': 'var(--tw-color-zinc-500)',
  '--theme-link-foreground': 'var(--tw-color-sky-600)',
  '--theme-content-background': 'white',
  '--theme-widget-panel-background': 'var(--tw-color-zinc-800)',
  '--theme-widget-panel-foreground': 'var(--tw-color-zinc-500)',
  '--theme-widget-icon-background-active': 'var(--tw-color-zinc-600)',
  '--theme-widget-icon-foreground-active': 'white',
  '--theme-widget-icon-foreground-hover': 'white',
  '--theme-widget-icon-border-active': '1px solid white',
  '--theme-widget-icon-transition': 'background-color 150ms ease-in-out, color 150ms ease-in-out',
  '--theme-scrollbar-background': 'var(--tw-color-zinc-200)',
  '--theme-scrollbar-thumb-background': 'var(--tw-color-zinc-400)',
  '--theme-scrollbar-thumb-background-hover': 'var(--tw-color-zinc-500)',
  '--theme-scrollbar-corner-background': 'var(--tw-color-zinc-300)',
  '--theme-tabs-panel-border': '1px solid var(--tw-color-zinc-50)',
  '--theme-tabs-panel-foreground': 'var(--tw-color-zinc-700)',
  '--theme-tabs-panel-active-foreground': 'var(--tw-color-zinc-950)',
  '--theme-tabs-panel-background': 'var(--tw-color-zinc-100)',
  '--theme-tabs-panel-active-background': 'var(--tw-color-zinc-50)',
  '--theme-tabs-panel-item-background': 'var(--tw-color-zinc-200)',
  '--theme-tabs-panel-active-border': '1px solid var(--tw-color-sky-500)',
  '--theme-tabs-panel-active-border-db': 'none',
  '--theme-splitter-active': 'var(--tw-color-sky-500)',
  '--theme-splitter-button-background': 'var(--tw-color-zinc-200)',
  '--theme-splitter-button-background-active': 'var(--tw-color-zinc-300)',
  '--theme-splitter-button-foreground': 'var(--tw-color-zinc-950)',
  '--theme-sidebar-background': 'var(--tw-color-zinc-200)',
  '--theme-sidebar-background-hover': 'var(--tw-color-zinc-300)',
  '--theme-sidebar-background-active': 'var(--tw-color-zinc-300)',
  '--theme-sidebar-background-focused': 'var(--tw-color-sky-200)',
  '--theme-sidebar-foreground': 'var(--tw-color-zinc-900)',
  '--theme-sidebar-foreground-button': 'var(--tw-color-zinc-600)',
  '--theme-sidebar-foreground-grayed': 'var(--tw-color-zinc-400)',
  '--theme-sidebar-foreground-hover': 'var(--tw-color-sky-600)',
  '--theme-sidebar-section-background': 'var(--tw-color-zinc-400)',
  '--theme-sidebar-section-border': 'none',
  '--theme-sidebar-section-border-top': '1px solid var(--tw-color-zinc-300)',
  '--theme-sidebar-section-foreground': 'var(--tw-color-zinc-950)',
  '--theme-sidebar-border': 'none',
  '--theme-altsidebar-background': 'white',
  '--theme-altsidebar-background-grayed': 'var(--tw-color-zinc-100)',
  '--theme-altsidebar-background-hover': 'var(--tw-color-zinc-300)',
  '--theme-altsidebar-background-active': 'var(--tw-color-zinc-300)',
  '--theme-altsidebar-background-focused': 'var(--tw-color-sky-200)',
  '--theme-altsidebar-foreground': 'var(--tw-color-zinc-900)',
  '--theme-altsidebar-foreground-button': 'var(--tw-color-zinc-600)',
  '--theme-altsidebar-foreground-grayed': 'var(--tw-color-zinc-400)',
  '--theme-altsidebar-foreground-hover': 'var(--tw-color-sky-600)',
  '--theme-altsidebar-section-background': 'var(--tw-color-zinc-100)',
  '--theme-altsidebar-section-border': 'none',
  '--theme-altsidebar-section-border-top': '1px solid var(--tw-color-zinc-300)',
  '--theme-altsidebar-section-foreground': 'var(--tw-color-zinc-950)',
  '--theme-altsidebar-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-searchbox-background': 'var(--tw-color-zinc-300)',
  '--theme-searchbox-placeholder': 'var(--tw-color-zinc-500)',
  '--theme-searchbox-border': '1px solid var(--tw-color-zinc-400)',
  '--theme-searchbox-background-filtered': 'var(--tw-color-amber-100)',
  '--theme-altsearchbox-background': 'var(--tw-color-zinc-200)',
  '--theme-altsearchbox-placeholder': 'var(--tw-color-zinc-500)',
  '--theme-altsearchbox-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-inlinebutton-foreground': 'var(--tw-color-zinc-600)',
  '--theme-inlinebutton-foreground-disabled': 'var(--tw-color-zinc-500)',
  '--theme-inlinebutton-foreground-hover': 'black',
  '--theme-inlinebutton-circle-hover-background': 'var(--tw-color-zinc-300)',
  '--theme-inlinebutton-bordered-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-inlinebutton-bordered-hover-border': '1px solid var(--tw-color-zinc-400)',
  '--theme-inlinebutton-bordered-background':
    'linear-gradient(to bottom, var(--tw-color-zinc-100) 5%, var(--tw-color-zinc-200) 100%)',
  '--theme-inlinebutton-bordered-hover-background':
    'linear-gradient(to bottom, var(--tw-color-zinc-200) 5%, var(--tw-color-zinc-100) 100%)',
  '--theme-datagrid-background': 'var(--tw-color-zinc-100)',
  '--theme-datagrid-foreground': 'var(--tw-color-zinc-900)',
  '--theme-datagrid-foreground-grayed': 'var(--tw-color-zinc-400)',
  '--theme-datagrid-border-horizontal': '1px solid var(--tw-color-zinc-200)',
  '--theme-datagrid-border-vertical': '1px solid var(--tw-color-zinc-100)',
  '--theme-datagrid-cell-background': 'white',
  '--theme-datagrid-headercell-background': 'var(--tw-color-zinc-100)',
  '--theme-datagrid-cell-background-alt': 'var(--tw-color-zinc-100)',
  '--theme-datagrid-cell-background-alt2': 'var(--tw-color-blue-50)',
  '--theme-datagrid-filter-background': 'var(--tw-color-zinc-200)',
  '--theme-datagrid-filter-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-datagrid-filter-ok-background': 'var(--tw-color-amber-100)',
  '--theme-datagrid-filter-error-background': 'var(--tw-color-rose-100)',
  '--theme-datagrid-modified-row-background': 'var(--tw-color-amber-100)',
  '--theme-datagrid-modified-cell-background': 'var(--tw-color-amber-200)',
  '--theme-datagrid-inserted-row-background': 'var(--tw-color-green-100)',
  '--theme-datagrid-deleted-row-background': 'var(--tw-color-red-100)',
  '--theme-datagrid-selected-cell-background': 'var(--tw-color-zinc-300)',
  '--theme-datagrid-focused-cell-background': 'var(--tw-color-sky-200)',
  '--theme-datagrid-focused-cell-border-horizontal': '1px solid var(--tw-color-sky-300)',
  '--theme-datagrid-focused-cell-border-vertical': '1px solid var(--tw-color-sky-300)',
  '--theme-datagrid-selected-point-marker': 'var(--tw-color-sky-500)',
  '--theme-datagrid-corner-label-background': 'var(--tw-color-sky-200)',
  '--theme-datagrid-corner-label-border': '1px solid var(--tw-color-sky-300)',
  '--theme-datagrid-detail-header-background': 'var(--tw-color-blue-100)',
  '--theme-datagrid-detail-header-border': '1px solid var(--tw-color-blue-200)',
  '--theme-checkbox-check': 'var(--tw-color-zinc-200)',
  '--theme-checkbox-background': 'var(--tw-color-sky-600)',
  '--theme-checkbox-border': '2px solid var(--tw-color-zinc-700)',
  '--theme-checkbox-mark': 'white',
  '--theme-table-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-table-cell-background': 'white',
  '--theme-table-cell-empty-background': 'var(--tw-color-zinc-100)',
  '--theme-table-cell-empty-foreground': 'var(--tw-color-zinc-500)',
  '--theme-table-header-background': 'var(--tw-color-zinc-100)',
  '--theme-table-selected-background': 'var(--tw-color-sky-200)',
  '--theme-table-active-background': 'var(--tw-color-zinc-200)',
  '--theme-table-hover-background': 'var(--tw-color-zinc-100)',
  '--theme-table-added-background': 'var(--theme-datagrid-inserted-row-background)',
  '--theme-table-changed-background': 'var(--theme-datagrid-modified-row-background)',
  '--theme-table-deleted-background': 'var(--theme-datagrid-deleted-row-background)',
  '--theme-cell-active-border': '2px solid var(--tw-color-sky-500)',
  '--theme-object-header-background': 'var(--tw-color-zinc-100)',
  '--theme-input-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-input-background': 'var(--tw-color-zinc-100)',
  '--theme-input-background-disabled': 'var(--tw-color-zinc-200)',
  '--theme-input-foreground-disabled': 'var(--tw-color-zinc-500)',
  '--theme-modal-background': 'white',
  '--theme-modal-header-background': 'var(--tw-color-zinc-300)',
  '--theme-modal-footer-background': 'white',
  '--theme-modal-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-modal-close-hover-background': 'var(--tw-color-zinc-400)',
  '--theme-formbutton-foreground': 'white',
  '--theme-formbutton-border': '1px solid var(--tw-color-sky-600)',
  '--theme-formbutton-border-hover': '1px solid var(--tw-color-sky-500)',
  '--theme-formbutton-border-active': '2px solid var(--tw-color-sky-400)',
  '--theme-formbutton-background': 'var(--tw-color-sky-700)',
  '--theme-formbutton-background-disabled': 'var(--tw-color-zinc-300)',
  '--theme-formbutton-border-disabled': '1px solid var(--tw-color-zinc-300)',
  '--theme-formbutton-foreground-disabled': 'var(--tw-color-zinc-500)',
  '--theme-formbutton-background-hover': 'var(--tw-color-sky-800)',
  '--theme-formbutton-background-active': 'var(--tw-color-sky-800)',
  '--theme-outlinebutton-foreground': 'var(--tw-color-zinc-950)',
  '--theme-outlinebutton-border': '1px solid var(--tw-color-sky-700)',
  '--theme-outlinebutton-hover-foreground': 'var(--tw-color-sky-700)',
  '--theme-outlinebutton-hover-border': '2px solid var(--tw-color-sky-600)',
  '--theme-tabs-control-background': 'var(--tw-color-zinc-100)',
  '--theme-tabs-control-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-tabs-control-selected-background': 'var(--tw-color-zinc-50)',
  '--theme-tabs-control-selected-border': '2px solid var(--tw-color-sky-500)',
  '--theme-inline-tabs-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-inline-tabs-border-active': '2px solid var(--tw-color-sky-500)',
  '--theme-toolstrip-background': 'white',
  '--theme-toolstrip-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-toolstrip-button-foreground': 'var(--tw-color-zinc-700)',
  '--theme-toolstrip-button-foreground-disabled': 'var(--tw-color-zinc-400)',
  '--theme-toolstrip-button-foreground-icon': 'var(--tw-color-zinc-600)',
  '--theme-toolstrip-button-background': 'white',
  '--theme-toolstrip-button-background-hover': 'var(--tw-color-zinc-100)',
  '--theme-toolstrip-button-background-active': 'var(--tw-color-zinc-200)',
  '--theme-toolstrip-button-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-toolstrip-button-border-hover': '1px solid var(--tw-color-zinc-300)',
  '--theme-toolstrip-button-border-disabled': '1px solid var(--tw-color-zinc-200)',
  '--theme-toolstrip-button-split-separator-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-designer-background': 'white',
  '--theme-designer-item-background': 'var(--tw-color-zinc-100)',
  '--theme-designer-selection-marker': 'var(--tw-color-sky-800)',
  '--theme-designer-item-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-designer-stroke-color': 'var(--tw-color-zinc-400)',
  '--theme-designer-arrow-color': 'var(--tw-color-zinc-800)',
  '--theme-designer-select-reactangle-foreground': 'var(--tw-color-sky-500)',
  '--theme-designer-header-background-1': 'var(--tw-color-sky-200)',
  '--theme-designer-header-background-2': 'var(--tw-color-fuchsia-200)',
  '--theme-designer-header-background-3': 'var(--tw-color-red-200)',
  '--theme-designer-header-background-grayed': 'var(--tw-color-zinc-300)',
  '--theme-designer-close-background': 'var(--tw-color-zinc-200)',
  '--theme-designer-close-background-hover': 'var(--tw-color-zinc-300)',
  '--theme-designer-close-background-active': 'var(--tw-color-zinc-400)',
  '--theme-statusbar-background': 'var(--tw-color-sky-700)',
  '--theme-statusbar-foreground': 'var(--tw-color-zinc-100)',
  '--theme-statusbar-background-hover': 'var(--tw-color-sky-800)',
  '--theme-statusbar-button-background': 'var(--tw-color-zinc-300)',
  '--theme-statusbar-button-foreground': 'var(--tw-color-zinc-800)',
  '--theme-statusbar-icon-error': 'var(--tw-color-red-300)',
  '--theme-statusbar-icon-ok': 'var(--tw-color-green-300)',
  '--theme-aichat-user-background': 'var(--tw-color-sky-100)',
  '--theme-aichat-assistant-background': 'var(--tw-color-zinc-100)',
  '--theme-font-1': '#262626',
  '--theme-font-2': '#4d4d4d',
  '--theme-font-3': '#808080',
  '--theme-font-4': '#b3b3b3',
  '--theme-font-hover': '#061178',
  '--theme-font-link': '#10239e',
  '--theme-font-alt': '#135200',
  '--theme-bg-0': '#fff',
  '--theme-bg-1': '#ededed',
  '--theme-bg-2': '#d4d4d4',
  '--theme-bg-3': '#bbbbbb',
  '--theme-bg-4': '#a2a2a2',
  '--theme-bg-alt': '#f0f5ff',
  '--theme-bg-gold': '#fff1b8',
  '--theme-bg-orange': '#ffe7ba',
  '--theme-bg-green': '#d9f7be',
  '--theme-bg-volcano': '#ffd8bf',
  '--theme-bg-red': '#ffccc7',
  '--theme-bg-blue': '#91d5ff',
  '--theme-bg-magenta': '#ffadd2',
  '--theme-font-inv-1': '#ffffff',
  '--theme-font-inv-15': '#dedede',
  '--theme-font-inv-2': '#b3b3b3',
  '--theme-font-inv-3': '#808080',
  '--theme-font-inv-4': '#4d4d4d',
  '--theme-bg-inv-1': '#222',
  '--theme-bg-inv-2': '#3c3c3c',
  '--theme-bg-inv-3': '#565656',
  '--theme-bg-inv-4': '#707070',
  '--theme-border': '#ccc',
  '--theme-bg-hover': '#ccc',
  '--theme-bg-selected': '#91d5ff',
  '--theme-bg-selected-point': '#40a9ff',
  '--theme-bg-statusbar-inv': '#0050b3',
  '--theme-bg-statusbar-inv-hover': '#096dd9',
  '--theme-bg-statusbar-inv-font': '#222',
  '--theme-bg-statusbar-inv-bg': '#ccc',
  '--theme-bg-modalheader': '#eff',
  '--theme-bg-button-inv': '#337ab7',
  '--theme-bg-button-inv-2': '#4d8bc0',
  '--theme-bg-button-inv-3': '#679cc9',
  '--theme-icon-blue': 'var(--tw-color-sky-700)',
  '--theme-icon-green': 'var(--tw-color-green-700)',
  '--theme-icon-red': 'var(--tw-color-red-700)',
  '--theme-icon-gold': 'var(--tw-color-amber-700)',
  '--theme-icon-yellow': 'var(--tw-color-yellow-700)',
  '--theme-icon-magenta': 'var(--tw-color-pink-700)',
  '--token-base': 'white',
  '--token-text': 'black',
  '--token-comment': '#008000',
  '--token-quote': '#008000',
  '--token-variable': '#008000',
  '--token-keyword': '#00f',
  '--token-selector-tag': '#00f',
  '--token-built_in': '#00f',
  '--token-name': '#00f',
  '--token-tag': '#00f',
  '--token-string': '#a31515',
  '--token-title': '#a31515',
  '--token-section': '#a31515',
  '--token-attribute': '#a31515',
  '--token-literal': '#a31515',
  '--token-template-tag': '#a31515',
  '--token-template-variable': '#a31515',
  '--token-type': '#a31515',
  '--token-addition': '#a31515',
  '--token-deletion': '#2b91af',
  '--token-selector-attr': '#2b91af',
  '--token-selector-pseudo': '#2b91af',
  '--token-meta': '#2b91af',
  '--token-doctag': '#808080',
  '--token-attr': '#f00',
  '--token-symbol': '#00b0e8',
  '--token-bullet': '#00b0e8',
  '--token-link': '#00b0e8',
  '--token-emphasis': 'italic',
  '--token-strong': 'bold',
};
