export const themeDarkColors = {
  '--theme-generic-font': 'var(--tw-color-zinc-50)',
  '--theme-generic-font-hover': 'var(--tw-color-sky-400)',
  '--theme-generic-font-grayed': 'var(--tw-color-zinc-500)',
  '--theme-link-foreground': 'var(--tw-color-sky-400)',
  '--theme-content-background': 'var(--tw-color-zinc-950)',
  '--theme-widget-panel-background': 'var(--tw-color-zinc-700)',
  '--theme-widget-panel-foreground': 'var(--tw-color-zinc-400)',
  '--theme-widget-icon-background-active': 'var(--tw-color-zinc-600)',
  '--theme-widget-icon-foreground-active': 'white',
  '--theme-widget-icon-foreground-hover': 'white',
  '--theme-widget-icon-border-active': '1px solid white',
  '--theme-widget-icon-transition': 'background-color 150ms ease-in-out, color 150ms ease-in-out',
  '--theme-scrollbar-background': 'var(--tw-color-zinc-800)',
  '--theme-scrollbar-thumb-background': 'var(--tw-color-zinc-600)',
  '--theme-scrollbar-thumb-background-hover': 'var(--tw-color-zinc-500)',
  '--theme-scrollbar-corner-background': 'var(--tw-color-zinc-700)',
  '--theme-tabs-panel-border': '1px solid var(--tw-color-zinc-950)',
  '--theme-tabs-panel-foreground': 'var(--tw-color-zinc-300)',
  '--theme-tabs-panel-active-foreground': 'white',
  '--theme-tabs-panel-background': 'var(--tw-color-zinc-900)',
  '--theme-tabs-panel-active-background': 'var(--tw-color-zinc-950)',
  '--theme-tabs-panel-item-background': 'var(--tw-color-zinc-800)',
  '--theme-tabs-panel-active-border': '1px solid var(--tw-color-sky-500)',
  '--theme-tabs-panel-active-border-db': 'none',
  '--theme-splitter-active': 'var(--tw-color-sky-500)',
  '--theme-splitter-button-background': 'var(--tw-color-zinc-800)',
  '--theme-splitter-button-background-active': 'var(--tw-color-zinc-700)',
  '--theme-splitter-button-foreground': 'var(--tw-color-zinc-50)',
  '--theme-sidebar-background': 'var(--tw-color-zinc-800)',
  '--theme-sidebar-background-hover': 'var(--tw-color-zinc-700)',
  '--theme-sidebar-background-active': 'var(--tw-color-zinc-700)',
  '--theme-sidebar-background-focused': 'var(--tw-color-sky-800)',
  '--theme-sidebar-foreground': 'var(--tw-color-zinc-100)',
  '--theme-sidebar-foreground-button': 'var(--tw-color-zinc-400)',
  '--theme-sidebar-foreground-grayed': 'var(--tw-color-zinc-500)',
  '--theme-sidebar-foreground-hover': 'var(--tw-color-sky-400)',
  '--theme-sidebar-section-background': 'var(--tw-color-zinc-800)',
  '--theme-sidebar-section-border': 'none',
  '--theme-sidebar-section-border-top': '1px solid var(--tw-color-zinc-700)',
  '--theme-sidebar-section-foreground': 'var(--tw-color-zinc-50)',
  '--theme-sidebar-border': 'none',
  '--theme-altsidebar-background': 'var(--tw-color-zinc-950)',
  '--theme-altsidebar-background-grayed': 'var(--tw-color-zinc-900)',
  '--theme-altsidebar-background-hover': 'var(--tw-color-zinc-700)',
  '--theme-altsidebar-background-active': 'var(--tw-color-zinc-700)',
  '--theme-altsidebar-background-focused': 'var(--tw-color-sky-800)',
  '--theme-altsidebar-foreground': 'var(--tw-color-zinc-100)',
  '--theme-altsidebar-foreground-button': 'var(--tw-color-zinc-400)',
  '--theme-altsidebar-foreground-grayed': 'var(--tw-color-zinc-500)',
  '--theme-altsidebar-foreground-hover': 'var(--tw-color-sky-400)',
  '--theme-altsidebar-section-background': 'var(--tw-color-zinc-950)',
  '--theme-altsidebar-section-border': 'none',
  '--theme-altsidebar-section-border-top': '1px solid var(--tw-color-zinc-700)',
  '--theme-altsidebar-section-foreground': 'var(--tw-color-zinc-50)',
  '--theme-altsidebar-border': '1px solid var(--tw-color-zinc-800)',
  '--theme-searchbox-background': 'var(--tw-color-zinc-700)',
  '--theme-searchbox-placeholder': 'var(--tw-color-zinc-500)',
  '--theme-searchbox-border': '1px solid var(--tw-color-zinc-600)',
  '--theme-searchbox-background-filtered': 'var(--tw-color-yellow-950)',
  '--theme-altsearchbox-background': 'var(--tw-color-zinc-800)',
  '--theme-altsearchbox-placeholder': 'var(--tw-color-zinc-500)',
  '--theme-altsearchbox-border': '1px solid var(--tw-color-zinc-700)',
  '--theme-inlinebutton-foreground': 'var(--tw-color-zinc-400)',
  '--theme-inlinebutton-foreground-disabled': 'var(--tw-color-zinc-500)',
  '--theme-inlinebutton-foreground-hover': 'white',
  '--theme-inlinebutton-circle-hover-background': 'var(--tw-color-zinc-700)',
  '--theme-inlinebutton-bordered-border': '1px solid var(--tw-color-zinc-700)',
  '--theme-inlinebutton-bordered-hover-border': '1px solid var(--tw-color-zinc-600)',
  '--theme-inlinebutton-bordered-background':
    'linear-gradient(to bottom, var(--tw-color-zinc-800) 5%, var(--tw-color-zinc-900) 100%)',
  '--theme-inlinebutton-bordered-hover-background':
    'linear-gradient(to bottom, var(--tw-color-zinc-900) 5%, var(--tw-color-zinc-800) 100%)',
  '--theme-datagrid-background': 'var(--tw-color-zinc-900)',
  '--theme-datagrid-foreground': 'var(--tw-color-zinc-100)',
  '--theme-datagrid-foreground-grayed': 'var(--tw-color-zinc-400)',
  '--theme-datagrid-border-horizontal': '1px solid var(--tw-color-zinc-800)',
  '--theme-datagrid-border-vertical': '1px solid var(--tw-color-zinc-900)',
  '--theme-datagrid-cell-background': 'var(--tw-color-zinc-950)',
  '--theme-datagrid-headercell-background': 'var(--tw-color-zinc-900)',
  '--theme-datagrid-cell-background-alt': 'var(--tw-color-zinc-900)',
  '--theme-datagrid-cell-background-alt2':
    'color-mix(in hsl, var(--tw-color-blue-950) 50%, var(--tw-color-zinc-950) 50%)',
  '--theme-datagrid-filter-background': 'var(--tw-color-zinc-800)',
  '--theme-datagrid-filter-border': '1px solid var(--tw-color-zinc-700)',
  '--theme-datagrid-filter-ok-background': 'var(--tw-color-yellow-950)',
  '--theme-datagrid-filter-error-background': 'var(--tw-color-rose-950)',
  '--theme-datagrid-modified-row-background': 'var(--tw-color-yellow-950)',
  '--theme-datagrid-modified-cell-background': 'var(--tw-color-yellow-900)',
  '--theme-datagrid-inserted-row-background': 'var(--tw-color-green-950)',
  '--theme-datagrid-deleted-row-background': 'var(--tw-color-red-950)',
  '--theme-datagrid-selected-cell-background': 'var(--tw-color-zinc-700)',
  '--theme-datagrid-focused-cell-background': 'var(--tw-color-sky-900)',
  '--theme-datagrid-focused-cell-border-horizontal': '1px solid var(--tw-color-sky-700)',
  '--theme-datagrid-focused-cell-border-vertical': '1px solid var(--tw-color-sky-700)',
  '--theme-datagrid-selected-point-marker': 'var(--tw-color-sky-500)',
  '--theme-datagrid-corner-label-background': 'var(--tw-color-sky-900)',
  '--theme-datagrid-corner-label-border': '1px solid var(--tw-color-sky-700)',
  '--theme-datagrid-detail-header-background': 'var(--tw-color-blue-950)',
  '--theme-datagrid-detail-header-border': '1px solid var(--tw-color-blue-900)',
  '--theme-datagrid-cell-foreground-value-green': 'var(--tw-color-green-400)',
  '--theme-checkbox-check': 'var(--tw-color-zinc-800)',
  '--theme-checkbox-background': 'var(--tw-color-sky-600)',
  '--theme-checkbox-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-checkbox-mark': 'white',
  '--theme-checkbox-background-disabled': 'var(--tw-color-zinc-800)',
  '--theme-checkbox-background-disabled-before': 'var(--tw-color-zinc-600)',
  '--theme-checkbox-hover-not-disabled': 'var(--tw-color-zinc-500)',
  '--theme-chip-background': 'var(--tw-color-zinc-700)',
  '--theme-table-border': '1px solid var(--tw-color-zinc-800)',
  '--theme-table-cell-background': 'var(--tw-color-zinc-950)',
  '--theme-table-cell-empty-background': 'var(--tw-color-zinc-900)',
  '--theme-table-cell-empty-foreground': 'var(--tw-color-zinc-500)',
  '--theme-table-header-background': 'var(--tw-color-zinc-900)',
  '--theme-table-selected-background': 'var(--tw-color-sky-900)',
  '--theme-table-active-background': 'var(--tw-color-zinc-800)',
  '--theme-table-hover-background': 'var(--tw-color-zinc-900)',
  '--theme-table-added-background': 'var(--theme-datagrid-inserted-row-background)',
  '--theme-table-changed-background': 'var(--theme-datagrid-modified-row-background)',
  '--theme-table-deleted-background': 'var(--theme-datagrid-deleted-row-background)',
  '--theme-cell-active-border': '2px solid var(--tw-color-sky-500)',
  '--theme-object-header-background': 'var(--tw-color-zinc-800)',
  '--theme-modal-background': 'var(--tw-color-zinc-950)',
  '--theme-modal-header-background': 'var(--tw-color-zinc-800)',
  '--theme-modal-footer-background': 'var(--tw-color-zinc-950)',
  '--theme-modal-border': '1px solid var(--tw-color-zinc-700)',
  '--theme-modal-overlay-background': 'color-mix(in srgb, var(--tw-color-black) 30%, transparent)',
  '--theme-modal-shadow': '0 20px 25px -5px color-mix(in srgb, var(--tw-color-black) 25%, transparent)',
  '--theme-modal-close-hover-background': 'var(--tw-color-zinc-700)',
  '--theme-formbutton-foreground': 'white',
  '--theme-formbutton-border': '1px solid var(--tw-color-sky-600)',
  '--theme-formbutton-border-hover': '1px solid var(--tw-color-sky-500)',
  '--theme-formbutton-border-active': '2px solid var(--tw-color-sky-400)',
  '--theme-formbutton-background': 'var(--tw-color-sky-700)',
  '--theme-formbutton-background-disabled': 'var(--tw-color-zinc-700)',
  '--theme-formbutton-border-disabled': '1px solid var(--tw-color-zinc-700)',
  '--theme-formbutton-foreground-disabled': 'var(--tw-color-zinc-500)',
  '--theme-formbutton-background-hover': 'var(--tw-color-sky-800)',
  '--theme-formbutton-background-active': 'var(--tw-color-sky-800)',
  '--theme-new-object-button-background': 'var(--tw-color-zinc-800)',
  '--theme-new-object-button-background-hover': 'var(--tw-color-zinc-700)',
  '--theme-status-valid-background': 'var(--tw-color-green-950)',
  '--theme-status-testing-background': 'var(--tw-color-amber-950)',
  '--theme-status-error-background': 'var(--tw-color-red-950)',
  '--theme-status-unconfigured-background': 'var(--tw-color-zinc-800)',
  '--theme-status-untested-background': 'var(--tw-color-orange-950)',
  '--theme-dropdown-icon-hover': 'var(--tw-color-blue-400)',
  '--theme-color-selected-border': '2px solid var(--tw-color-zinc-200)',
    '--theme-icon-picker-background': 'var(--tw-color-zinc-900)',
    '--theme-icon-picker-border': '1px solid var(--tw-color-zinc-700)',
    '--theme-icon-picker-hover': 'var(--tw-color-zinc-800)',
    '--theme-icon-picker-selected': 'var(--tw-color-sky-900)',
  '--theme-dbkey-background': 'var(--tw-color-zinc-900)',
  '--theme-dbkey-border': '2px solid var(--tw-color-zinc-700)',
  '--theme-dbkey-icon-hover': 'var(--tw-color-zinc-500)',
  '--theme-outlinebutton-foreground': 'var(--tw-color-zinc-50)',
  '--theme-outlinebutton-border': '1px solid var(--tw-color-sky-700)',
  '--theme-outlinebutton-hover-foreground': 'var(--tw-color-sky-400)',
  '--theme-outlinebutton-hover-border': '2px solid var(--tw-color-sky-600)',
  '--theme-tabs-control-background': 'var(--tw-color-zinc-900)',
  '--theme-tabs-control-border': '1px solid var(--tw-color-zinc-800)',
  '--theme-tabs-control-selected-background': 'var(--tw-color-zinc-950)',
  '--theme-tabs-control-selected-border': '2px solid var(--tw-color-sky-500)',
  '--theme-inline-tabs-border': '1px solid var(--tw-color-zinc-800)',
  '--theme-inline-tabs-border-active': '2px solid var(--tw-color-sky-500)',
  '--theme-titlebar-background': 'var(--tw-color-zinc-700)',
  '--theme-titlebar-button-hover': 'var(--tw-color-zinc-600)',
  '--theme-card-background': 'var(--tw-color-zinc-600)',
  '--theme-card-border': '1px solid var(--tw-color-zinc-800)',
  '--theme-content-background-hover': 'var(--tw-color-zinc-800)',
  '--theme-toolstrip-background': 'var(--tw-color-zinc-900)',
  '--theme-toolstrip-border': '1px solid var(--tw-color-zinc-800)',
  '--theme-toolstrip-button-foreground': 'var(--tw-color-zinc-200)',
  '--theme-panel-border-subtle': '1px solid color-mix(in srgb, var(--tw-color-zinc-100) 5%, transparent)',
  '--theme-panel-type-label-color': 'var(--tw-color-zinc-400)',
  '--theme-toolstrip-button-foreground-disabled': 'var(--tw-color-zinc-400)',
  '--theme-toolstrip-button-foreground-icon': 'var(--tw-color-zinc-400)',
  '--theme-toolstrip-button-background': 'var(--tw-color-zinc-800)',
  '--theme-toolstrip-button-background-hover': 'var(--tw-color-zinc-700)',
  '--theme-toolstrip-button-background-active': 'var(--tw-color-zinc-600)',
  '--theme-toolstrip-button-border': '1px solid var(--tw-color-zinc-600)',
  '--theme-toolstrip-button-border-hover': '1px solid var(--tw-color-zinc-500)',
  '--theme-toolstrip-button-border-disabled': '1px solid var(--tw-color-zinc-600)',
  '--theme-toolstrip-button-split-separator-border': '1px solid var(--tw-color-zinc-600)',
  '--theme-designer-background': 'var(--tw-color-zinc-950)',
  '--theme-designer-item-background': 'var(--tw-color-zinc-900)',
  '--theme-designer-selection-marker': 'var(--tw-color-sky-200)',
  '--theme-designer-item-border': '1px solid var(--tw-color-zinc-800)',
  '--theme-designer-stroke-color': 'var(--tw-color-zinc-600)',
  '--theme-designer-arrow-color': 'var(--tw-color-zinc-200)',
  '--theme-designer-select-reactangle-foreground': 'var(--tw-color-sky-500)',
  '--theme-designer-header-background-1': 'var(--tw-color-sky-800)',
  '--theme-designer-header-background-2': 'var(--tw-color-fuchsia-800)',
  '--theme-designer-header-background-3': 'var(--tw-color-red-800)',
  '--theme-designer-header-background-grayed': 'var(--tw-color-zinc-700)',
  '--theme-designer-close-background': 'var(--tw-color-zinc-800)',
  '--theme-designer-close-background-hover': 'var(--tw-color-zinc-700)',
  '--theme-designer-close-background-active': 'var(--tw-color-zinc-600)',
  '--theme-designer-drag-column-background': 'var(--tw-color-yellow-900)',
  '--theme-designer-select-column-background': 'var(--tw-color-zinc-800)',
  '--theme-statusbar-background': 'var(--tw-color-sky-700)',
  '--theme-statusbar-foreground': 'var(--tw-color-zinc-100)',
  '--theme-statusbar-background-hover': 'var(--tw-color-sky-800)',
  '--theme-statusbar-button-background': 'var(--tw-color-zinc-300)',
  '--theme-statusbar-button-foreground': 'var(--tw-color-zinc-800)',
  '--theme-statusbar-icon-error': 'var(--tw-color-red-300)',
  '--theme-statusbar-icon-ok': 'var(--tw-color-green-300)',
  '--theme-aichat-user-background': 'var(--tw-color-sky-900)',
  '--theme-aichat-assistant-background': 'var(--tw-color-zinc-900)',
  '--theme-applog-details-background': 'var(--tw-color-zinc-900)',
  '--theme-input-border': '1px solid var(--tw-color-zinc-700)',
  '--theme-input-border-hover': '1px solid var(--theme-input-border-hover-color)',
  '--theme-input-border-hover-color': 'var(--tw-color-zinc-600)',
  '--theme-input-border-focus': '1px solid var(--theme-input-border-focus-color)',
  '--theme-input-border-focus-color': 'var(--tw-color-sky-500)',
  '--theme-input-border-disabled': '1px solid var(--tw-color-zinc-800)',
  '--theme-input-background': 'var(--tw-color-zinc-950)',
  '--theme-input-foreground': 'var(--tw-color-zinc-100)',
  '--theme-input-placeholder': 'var(--tw-color-zinc-500)',
  '--theme-input-background-disabled': 'var(--tw-color-zinc-800)',
  '--theme-input-foreground-disabled': 'var(--tw-color-zinc-500)',
  '--theme-input-focus-ring': '0 0 0 3px color-mix(in srgb, var(--tw-color-sky-500) 15%, transparent)',
  '--theme-input-multi-clear-background': 'var(--tw-color-zinc-700)',
  '--theme-input-multi-clear-foreground': 'var(--tw-color-zinc-400)',
  '--theme-input-multi-clear-hover': 'var(--tw-color-zinc-600)',
  '--theme-input-shadow': '0 1px 2px 0 color-mix(in srgb, var(--tw-color-zinc-950) 35%, transparent)',
  '--theme-input-shadow-hover': '0 4px 6px -2px color-mix(in srgb, var(--tw-color-zinc-950) 40%, transparent)',
  '--theme-input-shadow-focus': '0 1px 2px 0 color-mix(in srgb, var(--tw-color-zinc-950) 35%, transparent)',
  '--theme-font-1': '#e3e3e3',
  '--theme-font-2': '#b5b5b5',
  '--theme-font-3': '#888888',
  '--theme-font-4': '#5a5a5a',
  '--theme-font-hover': '#8dcff8',
  '--theme-font-link': '#65b7f3',
  '--theme-font-alt': '#b2e58b',
  '--theme-bg-0': '#111',
  '--theme-bg-1': '#333',
  '--theme-bg-2': '#4d4d4d',
  '--theme-bg-3': '#676767',
  '--theme-bg-4': '#818181',
  '--theme-bg-alt': '#111d2c',
  '--theme-bg-gold': '#443111',
  '--theme-bg-orange': '#442a11',
  '--theme-bg-green': '#1d3712',
  '--theme-bg-volcano': '#441d12',
  '--theme-bg-red': '#431418',
  '--theme-bg-blue': '#15395b',
  '--theme-bg-magenta': '#551c3b',
  '--theme-font-inv-1': '#ffffff',
  '--theme-font-inv-15': '#dedede',
  '--theme-font-inv-2': '#b3b3b3',
  '--theme-font-inv-3': '#808080',
  '--theme-font-inv-4': '#4d4d4d',
  '--theme-bg-inv-1': '#222',
  '--theme-bg-inv-2': '#3c3c3c',
  '--theme-bg-inv-3': '#565656',
  '--theme-bg-inv-4': '#707070',
  '--theme-border': '#555',
  '--theme-bg-hover': '#555',
  '--theme-bg-selected': '#1d4d7e',
  '--theme-bg-selected-point': '#1765ad',
  '--theme-bg-statusbar-inv': '#0050b3',
  '--theme-bg-statusbar-inv-hover': '#096dd9',
  '--theme-bg-statusbar-inv-font': '#222',
  '--theme-bg-statusbar-inv-bg': '#ccc',
  '--theme-bg-modalheader': 'rgb(43, 60, 61)',
  '--theme-bg-button-inv': '#004488',
  '--theme-bg-button-inv-2': '#1a5794',
  '--theme-bg-button-inv-3': '#346aa0',
  '--theme-icon-blue': '#3c9ae8',
  '--theme-icon-green': '#8fd460',
  '--theme-icon-red': '#e84749',
  '--theme-icon-gold': '#e8b339',
  '--theme-icon-yellow': '#e8d639',
  '--theme-icon-magenta': '#e0529c',
  '--token-base': '#303030',
  '--token-text': '#ddd',
  '--token-keyword': '#096dd9',
  '--token-selector-tag': 'white',
  '--token-literal': 'white',
  '--token-section': 'white',
  '--token-link': 'white',
  '--token-subst': '#ddd',
  '--token-string': '#d88',
  '--token-title': '#d88',
  '--token-name': '#d88',
  '--token-type': '#d88',
  '--token-attribute': '#d88',
  '--token-symbol': '#d88',
  '--token-bullet': '#d88',
  '--token-built_in': '#d88',
  '--token-addition': '#d88',
  '--token-variable': '#d88',
  '--token-template-tag': '#d88',
  '--token-template-variable': '#d88',
  '--token-comment': '#979797',
  '--token-quote': '#979797',
  '--token-deletion': '#979797',
  '--token-meta': '#979797',
  '--token-doctag': '#808080',
  '--token-attr': '#f88',
  '--token-tag': '#5ba7ea',
  '--token-selector-attr': '#6eb4ea',
  '--token-selector-pseudo': '#6eb4ea',
  '--token-emphasis': 'italic',
  '--token-strong': 'bold',
};
