import type { DatabaseInfo } from 'dbgate-types';

export const chinookDbInfo: DatabaseInfo = {
  tables: [
    {
      pureName: 'Customer',
      tableRowCount: '59',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'Customer',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'Customer',
          notNull: true,
          autoIncrement: true,
          columnName: 'CustomerId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: true,
          autoIncrement: false,
          columnName: 'FirstName',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: true,
          autoIncrement: false,
          columnName: 'LastName',
          columnComment: '',
          dataType: 'varchar(20)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'Company',
          columnComment: '',
          dataType: 'varchar(80)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'Address',
          columnComment: '',
          dataType: 'varchar(70)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'City',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'State',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'Country',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'PostalCode',
          columnComment: '',
          dataType: 'varchar(10)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'Phone',
          columnComment: '',
          dataType: 'varchar(24)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'Fax',
          columnComment: '',
          dataType: 'varchar(24)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: true,
          autoIncrement: false,
          columnName: 'Email',
          columnComment: '',
          dataType: 'varchar(60)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Customer',
          notNull: false,
          autoIncrement: false,
          columnName: 'SupportRepId',
          columnComment: '',
          dataType: 'int',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'Customer',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'CustomerId',
          },
        ],
      },
      foreignKeys: [
        {
          constraintName: 'FK_CustomerSupportRepId',
          constraintType: 'foreignKey',
          pureName: 'Customer',
          refTableName: 'Employee',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'SupportRepId',
              refColumnName: 'EmployeeId',
            },
          ],
        },
      ],
      indexes: [
        {
          constraintName: 'IFK_CustomerSupportRepId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'SupportRepId',
            },
          ],
          pureName: 'Customer',
          constraintType: 'index',
        },
      ],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_InvoiceCustomerId',
          constraintType: 'foreignKey',
          pureName: 'Invoice',
          refTableName: 'Customer',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'CustomerId',
              refColumnName: 'CustomerId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'Track',
      tableRowCount: '3483',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'Track',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'Track',
          notNull: true,
          autoIncrement: true,
          columnName: 'TrackId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Track',
          notNull: true,
          autoIncrement: false,
          columnName: 'Name',
          columnComment: '',
          dataType: 'varchar(200)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Track',
          notNull: false,
          autoIncrement: false,
          columnName: 'AlbumId',
          columnComment: '',
          dataType: 'int',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Track',
          notNull: true,
          autoIncrement: false,
          columnName: 'MediaTypeId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Track',
          notNull: false,
          autoIncrement: false,
          columnName: 'GenreId',
          columnComment: '',
          dataType: 'int',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Track',
          notNull: false,
          autoIncrement: false,
          columnName: 'Composer',
          columnComment: '',
          dataType: 'varchar(220)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Track',
          notNull: true,
          autoIncrement: false,
          columnName: 'Milliseconds',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Track',
          notNull: false,
          autoIncrement: false,
          columnName: 'Bytes',
          columnComment: '',
          dataType: 'int',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Track',
          notNull: true,
          autoIncrement: false,
          columnName: 'UnitPrice',
          columnComment: '',
          dataType: 'decimal(10,2)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'Track',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'TrackId',
          },
        ],
      },
      foreignKeys: [
        {
          constraintName: 'FK_TrackMediaTypeId',
          constraintType: 'foreignKey',
          pureName: 'Track',
          refTableName: 'MediaType',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'MediaTypeId',
              refColumnName: 'MediaTypeId',
            },
          ],
        },
        {
          constraintName: 'FK_TrackAlbumId',
          constraintType: 'foreignKey',
          pureName: 'Track',
          refTableName: 'Album',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'AlbumId',
              refColumnName: 'AlbumId',
            },
          ],
        },
        {
          constraintName: 'FK_TrackGenreId',
          constraintType: 'foreignKey',
          pureName: 'Track',
          refTableName: 'Genre',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'GenreId',
              refColumnName: 'GenreId',
            },
          ],
        },
      ],
      indexes: [
        {
          constraintName: 'IFK_TrackGenreId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'GenreId',
            },
          ],
          pureName: 'Track',
          constraintType: 'index',
        },
        {
          constraintName: 'IFK_TrackMediaTypeId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'MediaTypeId',
            },
          ],
          pureName: 'Track',
          constraintType: 'index',
        },
        {
          constraintName: 'IFK_TrackAlbumId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'AlbumId',
            },
          ],
          pureName: 'Track',
          constraintType: 'index',
        },
      ],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_InvoiceLineTrackId',
          constraintType: 'foreignKey',
          pureName: 'InvoiceLine',
          refTableName: 'Track',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'TrackId',
              refColumnName: 'TrackId',
            },
          ],
        },
        {
          constraintName: 'FK_PlaylistTrackTrackId',
          constraintType: 'foreignKey',
          pureName: 'PlaylistTrack',
          refTableName: 'Track',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'TrackId',
              refColumnName: 'TrackId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'InvoiceLine',
      tableRowCount: '2240',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'InvoiceLine',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'InvoiceLine',
          notNull: true,
          autoIncrement: true,
          columnName: 'InvoiceLineId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'InvoiceLine',
          notNull: true,
          autoIncrement: false,
          columnName: 'InvoiceId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'InvoiceLine',
          notNull: true,
          autoIncrement: false,
          columnName: 'TrackId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'InvoiceLine',
          notNull: true,
          autoIncrement: false,
          columnName: 'UnitPrice',
          columnComment: '',
          dataType: 'decimal(10,2)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'InvoiceLine',
          notNull: true,
          autoIncrement: false,
          columnName: 'Quantity',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'InvoiceLine',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'InvoiceLineId',
          },
        ],
      },
      foreignKeys: [
        {
          constraintName: 'FK_InvoiceLineInvoiceId',
          constraintType: 'foreignKey',
          pureName: 'InvoiceLine',
          refTableName: 'Invoice',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'InvoiceId',
              refColumnName: 'InvoiceId',
            },
          ],
        },
        {
          constraintName: 'FK_InvoiceLineTrackId',
          constraintType: 'foreignKey',
          pureName: 'InvoiceLine',
          refTableName: 'Track',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'TrackId',
              refColumnName: 'TrackId',
            },
          ],
        },
      ],
      indexes: [
        {
          constraintName: 'IFK_InvoiceLineTrackId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'TrackId',
            },
          ],
          pureName: 'InvoiceLine',
          constraintType: 'index',
        },
        {
          constraintName: 'IFK_InvoiceLineInvoiceId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'InvoiceId',
            },
          ],
          pureName: 'InvoiceLine',
          constraintType: 'index',
        },
      ],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'Album',
      tableRowCount: '347',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'Album',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'Album',
          notNull: true,
          autoIncrement: true,
          columnName: 'AlbumId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Album',
          notNull: true,
          autoIncrement: false,
          columnName: 'Title',
          columnComment: '',
          dataType: 'varchar(160)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Album',
          notNull: true,
          autoIncrement: false,
          columnName: 'ArtistId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'Album',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'AlbumId',
          },
        ],
      },
      foreignKeys: [
        {
          constraintName: 'FK_AlbumArtistId',
          constraintType: 'foreignKey',
          pureName: 'Album',
          refTableName: 'Artist',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'ArtistId',
              refColumnName: 'ArtistId',
            },
          ],
        },
      ],
      indexes: [
        {
          constraintName: 'IFK_AlbumArtistId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'ArtistId',
            },
          ],
          pureName: 'Album',
          constraintType: 'index',
        },
      ],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_TrackAlbumId',
          constraintType: 'foreignKey',
          pureName: 'Track',
          refTableName: 'Album',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'AlbumId',
              refColumnName: 'AlbumId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'Invoice',
      tableRowCount: '412',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'Invoice',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'Invoice',
          notNull: true,
          autoIncrement: true,
          columnName: 'InvoiceId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Invoice',
          notNull: true,
          autoIncrement: false,
          columnName: 'CustomerId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Invoice',
          notNull: true,
          autoIncrement: false,
          columnName: 'InvoiceDate',
          columnComment: '',
          dataType: 'datetime',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Invoice',
          notNull: false,
          autoIncrement: false,
          columnName: 'BillingAddress',
          columnComment: '',
          dataType: 'varchar(70)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Invoice',
          notNull: false,
          autoIncrement: false,
          columnName: 'BillingCity',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Invoice',
          notNull: false,
          autoIncrement: false,
          columnName: 'BillingState',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Invoice',
          notNull: false,
          autoIncrement: false,
          columnName: 'BillingCountry',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Invoice',
          notNull: false,
          autoIncrement: false,
          columnName: 'BillingPostalCode',
          columnComment: '',
          dataType: 'varchar(10)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Invoice',
          notNull: true,
          autoIncrement: false,
          columnName: 'Total',
          columnComment: '',
          dataType: 'decimal(10,2)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'Invoice',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'InvoiceId',
          },
        ],
      },
      foreignKeys: [
        {
          constraintName: 'FK_InvoiceCustomerId',
          constraintType: 'foreignKey',
          pureName: 'Invoice',
          refTableName: 'Customer',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'CustomerId',
              refColumnName: 'CustomerId',
            },
          ],
        },
      ],
      indexes: [
        {
          constraintName: 'IFK_InvoiceCustomerId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'CustomerId',
            },
          ],
          pureName: 'Invoice',
          constraintType: 'index',
        },
      ],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_InvoiceLineInvoiceId',
          constraintType: 'foreignKey',
          pureName: 'InvoiceLine',
          refTableName: 'Invoice',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'InvoiceId',
              refColumnName: 'InvoiceId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'Genre_copy',
      tableRowCount: '412',
      modifyDate: '2022-04-28 12:59:29',
      objectId: 'Genre_copy',
      contentHash: '2022-04-28 12:59:29',
      columns: [
        {
          pureName: 'Genre_copy',
          notNull: false,
          autoIncrement: false,
          columnName: 'GenreId',
          columnComment: '',
          dataType: 'longtext',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Genre_copy',
          notNull: false,
          autoIncrement: false,
          columnName: 'Name',
          columnComment: '',
          dataType: 'longtext',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      foreignKeys: [],
      indexes: [],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'MediaType',
      tableRowCount: '5',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'MediaType',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'MediaType',
          notNull: true,
          autoIncrement: true,
          columnName: 'MediaTypeId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'MediaType',
          notNull: false,
          autoIncrement: false,
          columnName: 'Name',
          columnComment: '',
          dataType: 'varchar(120)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'MediaType',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'MediaTypeId',
          },
        ],
      },
      foreignKeys: [],
      indexes: [],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_TrackMediaTypeId',
          constraintType: 'foreignKey',
          pureName: 'Track',
          refTableName: 'MediaType',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'MediaTypeId',
              refColumnName: 'MediaTypeId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'Genre',
      tableRowCount: '25',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'Genre',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'Genre',
          notNull: true,
          autoIncrement: true,
          columnName: 'GenreId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Genre',
          notNull: false,
          autoIncrement: false,
          columnName: 'Name',
          columnComment: '',
          dataType: 'varchar(120)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'Genre',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'GenreId',
          },
        ],
      },
      foreignKeys: [],
      indexes: [],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_TrackGenreId',
          constraintType: 'foreignKey',
          pureName: 'Track',
          refTableName: 'Genre',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'GenreId',
              refColumnName: 'GenreId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'Playlist',
      tableRowCount: '18',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'Playlist',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'Playlist',
          notNull: true,
          autoIncrement: true,
          columnName: 'PlaylistId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Playlist',
          notNull: false,
          autoIncrement: false,
          columnName: 'Name',
          columnComment: '',
          dataType: 'varchar(120)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'Playlist',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'PlaylistId',
          },
        ],
      },
      foreignKeys: [],
      indexes: [],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_PlaylistTrackPlaylistId',
          constraintType: 'foreignKey',
          pureName: 'PlaylistTrack',
          refTableName: 'Playlist',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'PlaylistId',
              refColumnName: 'PlaylistId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'Artist',
      tableRowCount: '275',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'Artist',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'Artist',
          notNull: true,
          autoIncrement: true,
          columnName: 'ArtistId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Artist',
          notNull: false,
          autoIncrement: false,
          columnName: 'Name',
          columnComment: '',
          dataType: 'varchar(120)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'Artist',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'ArtistId',
          },
        ],
      },
      foreignKeys: [],
      indexes: [],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_AlbumArtistId',
          constraintType: 'foreignKey',
          pureName: 'Album',
          refTableName: 'Artist',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'ArtistId',
              refColumnName: 'ArtistId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'Employee',
      tableRowCount: '8',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'Employee',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'Employee',
          notNull: true,
          autoIncrement: true,
          columnName: 'EmployeeId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: true,
          autoIncrement: false,
          columnName: 'LastName',
          columnComment: '',
          dataType: 'varchar(20)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: true,
          autoIncrement: false,
          columnName: 'FirstName',
          columnComment: '',
          dataType: 'varchar(20)',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'Title',
          columnComment: '',
          dataType: 'varchar(30)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'ReportsTo',
          columnComment: '',
          dataType: 'int',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'BirthDate',
          columnComment: '',
          dataType: 'datetime',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'HireDate',
          columnComment: '',
          dataType: 'datetime',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'Address',
          columnComment: '',
          dataType: 'varchar(70)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'City',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'State',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'Country',
          columnComment: '',
          dataType: 'varchar(40)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'PostalCode',
          columnComment: '',
          dataType: 'varchar(10)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'Phone',
          columnComment: '',
          dataType: 'varchar(24)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'Fax',
          columnComment: '',
          dataType: 'varchar(24)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'Employee',
          notNull: false,
          autoIncrement: false,
          columnName: 'Email',
          columnComment: '',
          dataType: 'varchar(60)',
          defaultValue: 'NULL',
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'Employee',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'EmployeeId',
          },
        ],
      },
      foreignKeys: [
        {
          constraintName: 'FK_EmployeeReportsTo',
          constraintType: 'foreignKey',
          pureName: 'Employee',
          refTableName: 'Employee',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'ReportsTo',
              refColumnName: 'EmployeeId',
            },
          ],
        },
      ],
      indexes: [
        {
          constraintName: 'IFK_EmployeeReportsTo',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'ReportsTo',
            },
          ],
          pureName: 'Employee',
          constraintType: 'index',
        },
      ],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [
        {
          constraintName: 'FK_CustomerSupportRepId',
          constraintType: 'foreignKey',
          pureName: 'Customer',
          refTableName: 'Employee',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'SupportRepId',
              refColumnName: 'EmployeeId',
            },
          ],
        },
        {
          constraintName: 'FK_EmployeeReportsTo',
          constraintType: 'foreignKey',
          pureName: 'Employee',
          refTableName: 'Employee',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'ReportsTo',
              refColumnName: 'EmployeeId',
            },
          ],
        },
      ],
      objectTypeField: 'tables',
      checks: [],
    },
    {
      pureName: 'PlaylistTrack',
      tableRowCount: '8715',
      modifyDate: '2022-04-09 09:26:46',
      objectId: 'PlaylistTrack',
      contentHash: '2022-04-09 09:26:46',
      columns: [
        {
          pureName: 'PlaylistTrack',
          notNull: true,
          autoIncrement: false,
          columnName: 'PlaylistId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
        {
          pureName: 'PlaylistTrack',
          notNull: true,
          autoIncrement: false,
          columnName: 'TrackId',
          columnComment: '',
          dataType: 'int',
          defaultValue: null,
          isUnsigned: false,
          isZerofill: false,
        },
      ],
      primaryKey: {
        constraintName: 'PRIMARY',
        pureName: 'PlaylistTrack',
        constraintType: 'primaryKey',
        columns: [
          {
            columnName: 'PlaylistId',
          },
          {
            columnName: 'TrackId',
          },
        ],
      },
      foreignKeys: [
        {
          constraintName: 'FK_PlaylistTrackPlaylistId',
          constraintType: 'foreignKey',
          pureName: 'PlaylistTrack',
          refTableName: 'Playlist',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'PlaylistId',
              refColumnName: 'PlaylistId',
            },
          ],
        },
        {
          constraintName: 'FK_PlaylistTrackTrackId',
          constraintType: 'foreignKey',
          pureName: 'PlaylistTrack',
          refTableName: 'Track',
          updateAction: 'NO ACTION',
          deleteAction: 'NO ACTION',
          columns: [
            {
              columnName: 'TrackId',
              refColumnName: 'TrackId',
            },
          ],
        },
      ],
      indexes: [
        {
          constraintName: 'IFK_PlaylistTrackTrackId',
          indexType: 'BTREE',
          isUnique: false,
          columns: [
            {
              columnName: 'TrackId',
            },
          ],
          pureName: 'PlaylistTrack',
          constraintType: 'index',
        },
      ],
      uniques: [],
      engine: 'mariadb@dbgate-plugin-mysql',
      dependencies: [],
      objectTypeField: 'tables',
      checks: [],
    },
  ],
  views: [],
  procedures: [],
  functions: [],
  engine: 'mariadb@dbgate-plugin-mysql',
  collections: [],
  matviews: [],
  triggers: [],
  schedulerEvents: [],
};

// const ARTIST_TABLE: TableInfo = {
//     pureName: 'Artist',
//     columns: [
//       {
//         pureName: 'Artist',
//         notNull: true,
//         autoIncrement: true,
//         columnName: 'ArtistId',
//         columnComment: '',
//         dataType: 'int',
//       },
//       {
//         pureName: 'Artist',
//         notNull: false,
//         columnName: 'Name',
//         dataType: 'varchar(120)',
//       },
//     ],
//     primaryKey: {
//       constraintName: 'PRIMARY',
//       pureName: 'Artist',
//       constraintType: 'primaryKey',
//       columns: [
//         {
//           columnName: 'ArtistId',
//         },
//       ],
//     },
//     foreignKeys: [],
//     indexes: [],
//     uniques: [],
//     dependencies: [
//       {
//         constraintName: 'FK_AlbumArtistId',
//         constraintType: 'foreignKey',
//         pureName: 'Album',
//         refTableName: 'Artist',
//         columns: [
//           {
//             columnName: 'ArtistId',
//             refColumnName: 'ArtistId',
//           },
//         ],
//       },
//     ],
//     objectTypeField: 'tables',
//     checks: [],
//   };

//   const ALBUM_TABLE: TableInfo = {
//     pureName: 'Album',
//     columns: [
//       {
//         pureName: 'Album',
//         notNull: true,
//         autoIncrement: true,
//         columnName: 'AlbumId',
//         dataType: 'int',
//       },
//       {
//         pureName: 'Album',
//         notNull: true,
//         columnName: 'Title',
//         dataType: 'varchar(160)',
//       },
//       {
//         pureName: 'Album',
//         notNull: true,
//         autoIncrement: false,
//         columnName: 'ArtistId',
//         dataType: 'int',
//       },
//     ],
//     primaryKey: {
//       constraintName: 'PRIMARY',
//       pureName: 'Album',
//       constraintType: 'primaryKey',
//       columns: [
//         {
//           columnName: 'AlbumId',
//         },
//       ],
//     },
//     foreignKeys: [
//       {
//         constraintName: 'FK_AlbumArtistId',
//         constraintType: 'foreignKey',
//         pureName: 'Album',
//         refTableName: 'Artist',
//         columns: [
//           {
//             columnName: 'ArtistId',
//             refColumnName: 'ArtistId',
//           },
//         ],
//       },
//     ],
//     uniques: [],
//     dependencies: [
//       {
//         constraintName: 'FK_TrackAlbumId',
//         constraintType: 'foreignKey',
//         pureName: 'Track',
//         refTableName: 'Album',
//         columns: [
//           {
//             columnName: 'AlbumId',
//             refColumnName: 'AlbumId',
//           },
//         ],
//       },
//     ],
//     objectTypeField: 'tables',
//     checks: [],
//   };

//   const TRACK_TABLE: TableInfo = {
//     pureName: 'Track',
//     columns: [
//       {
//         pureName: 'Track',
//         notNull: true,
//         autoIncrement: true,
//         columnName: 'TrackId',
//         dataType: 'int',
//       },
//       {
//         pureName: 'Track',
//         notNull: true,
//         columnName: 'Name',
//         dataType: 'varchar(200)',
//       },
//       {
//         pureName: 'Track',
//         columnName: 'AlbumId',
//         dataType: 'int',
//       },
//       {
//         pureName: 'Track',
//         notNull: true,
//         columnName: 'MediaTypeId',
//         dataType: 'int',
//       },
//       {
//         pureName: 'Track',
//         columnName: 'GenreId',
//         dataType: 'int',
//       },
//       {
//         pureName: 'Track',
//         notNull: false,
//         autoIncrement: false,
//         columnName: 'Composer',
//         columnComment: '',
//         dataType: 'varchar(220)',
//         defaultValue: 'NULL',
//         isUnsigned: false,
//         isZerofill: false,
//       },
//       {
//         pureName: 'Track',
//         notNull: true,
//         autoIncrement: false,
//         columnName: 'Milliseconds',
//         columnComment: '',
//         dataType: 'int',
//         defaultValue: null,
//         isUnsigned: false,
//         isZerofill: false,
//       },
//       {
//         pureName: 'Track',
//         notNull: false,
//         autoIncrement: false,
//         columnName: 'Bytes',
//         columnComment: '',
//         dataType: 'int',
//         defaultValue: 'NULL',
//         isUnsigned: false,
//         isZerofill: false,
//       },
//       {
//         pureName: 'Track',
//         notNull: true,
//         autoIncrement: false,
//         columnName: 'UnitPrice',
//         columnComment: '',
//         dataType: 'decimal(10,2)',
//         defaultValue: null,
//         isUnsigned: false,
//         isZerofill: false,
//       },
//     ],
//     primaryKey: {
//       constraintName: 'PRIMARY',
//       pureName: 'Track',
//       constraintType: 'primaryKey',
//       columns: [
//         {
//           columnName: 'TrackId',
//         },
//       ],
//     },
//     foreignKeys: [
//       {
//         constraintName: 'FK_TrackMediaTypeId',
//         constraintType: 'foreignKey',
//         pureName: 'Track',
//         refTableName: 'MediaType',
//         updateAction: 'NO ACTION',
//         deleteAction: 'NO ACTION',
//         columns: [
//           {
//             columnName: 'MediaTypeId',
//             refColumnName: 'MediaTypeId',
//           },
//         ],
//       },
//       {
//         constraintName: 'FK_TrackAlbumId',
//         constraintType: 'foreignKey',
//         pureName: 'Track',
//         refTableName: 'Album',
//         updateAction: 'NO ACTION',
//         deleteAction: 'NO ACTION',
//         columns: [
//           {
//             columnName: 'AlbumId',
//             refColumnName: 'AlbumId',
//           },
//         ],
//       },
//       {
//         constraintName: 'FK_TrackGenreId',
//         constraintType: 'foreignKey',
//         pureName: 'Track',
//         refTableName: 'Genre',
//         updateAction: 'NO ACTION',
//         deleteAction: 'NO ACTION',
//         columns: [
//           {
//             columnName: 'GenreId',
//             refColumnName: 'GenreId',
//           },
//         ],
//       },
//     ],
//     uniques: [],
//     dependencies: [
//       {
//         constraintName: 'FK_InvoiceLineTrackId',
//         constraintType: 'foreignKey',
//         pureName: 'InvoiceLine',
//         refTableName: 'Track',
//         updateAction: 'NO ACTION',
//         deleteAction: 'NO ACTION',
//         columns: [
//           {
//             columnName: 'TrackId',
//             refColumnName: 'TrackId',
//           },
//         ],
//       },
//       {
//         constraintName: 'FK_PlaylistTrackTrackId',
//         constraintType: 'foreignKey',
//         pureName: 'PlaylistTrack',
//         refTableName: 'Track',
//         updateAction: 'NO ACTION',
//         deleteAction: 'NO ACTION',
//         columns: [
//           {
//             columnName: 'TrackId',
//             refColumnName: 'TrackId',
//           },
//         ],
//       },
//     ],
//     objectTypeField: 'tables',
//     checks: [],
//   };
