module.exports = `select 
	KEY_COLUMN_USAGE.CONSTRAINT_NAME as constraintName,
	KEY_COLUMN_USAGE.TABLE_NAME as pureName,
	KEY_COLUMN_USAGE.COLUMN_NAME as columnName
from INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
where KEY_COLUMN_USAGE.CONSTRAINT_SCHEMA = '#DATABASE#' and KEY_COLUMN_USAGE.TABLE_NAME =OBJECT_ID_CONDITION AND KEY_COLUMN_USAGE.CONSTRAINT_NAME = 'PRIMARY'
order by KEY_COLUMN_USAGE.ORDINAL_POSITION
`;
