module.exports = `
SELECT
    TRIM(rtr.RDB$TRIGGER_NAME) as PURENAME,
    TRIM(rtr.RDB$RELATION_NAME) as TABLENAME,
    rtr.RDB$TRIGGER_TYPE as TRIGGERTYPE,
    TRIM(rel.RDB$OWNER_NAME) AS SCHEMANAME
FROM
    RDB$TRIGGERS rtr
JOIN RDB$RELATIONS rel ON rtr.RDB$RELATION_NAME = rel.RDB$RELATION_NAME
WHERE rtr.RDB$SYSTEM_FLAG = 0
ORDER BY rtr.RDB$TRIGGER_NAME
`;
