module.exports = `
SELECT
    TRIM(rtr.RDB$TRIGGER_NAME) as "pureName",
    TRIM(rtr.RDB$RELATION_NAME) as "tableName",
    rtr.RDB$TRIGGER_TYPE as TRIGGERTYPE,
    CAST(rtr.RDB$TRIGGER_SOURCE AS VARCHAR(8191)) AS TRIGGER_BODY_SQL
FROM
    RDB$TRIGGERS rtr
JOIN RDB$RELATIONS rel ON rtr.RDB$RELATION_NAME = rel.RDB$RELATION_NAME
WHERE rtr.RDB$SYSTEM_FLAG = 0
AND ('triggers:' || TRIM(rtr.RDB$TRIGGER_NAME)) =OBJECT_ID_CONDITION
ORDER BY rtr.RDB$TRIGGER_NAME
`;
