module.exports = {
  engine: 'db2@dbgate-plugin-db2',
  title: 'IBM DB2',
  defaultPort: 50000,
  defaultDatabase: 'SAMPLE',
  dialect: 'db2',
  showConnectionTab: field => field == 'sshTunnel',
  connectionFields: [
    { field: 'server', type: 'string', label: 'Server', required: true },
    { field: 'port', type: 'number', label: 'Port', required: true, defaultValue: 50000 },
    { field: 'user', type: 'string', label: 'User', required: true },
    { field: 'password', type: 'password', label: 'Password', required: true },
    { field: 'database', type: 'string', label: 'Database', required: true, defaultValue: 'SAMPLE' },
  ],
  icon: 'db2',
  supports: {
    schemas: true,
    tables: true,
    views: true,
    triggers: true,
    procedures: true,
    functions: true,
    users: true,
    roles: true,
    indexes: true,
    foreignKeys: true,
    primaryKeys: true,
    uniqueKeys: true,
    checkConstraints: true,
    defaultValues: true,
    autoIncrement: true,
    comments: true,
    partitions: true,
    materializedViews: true,
    sequences: true,
    types: true,
    domains: true,
    collations: true,
    characterSets: true,
    extensions: true,
    privileges: true,
    grants: true
  },
  id: 'db2',
  name: 'DB2',
  displayName: 'IBM DB2',
  description: 'IBM DB2 Database',
  category: 'database',
  isBuiltin: true,
  sortOrder: -1
};